### ISSUE TITLE
need clarification 

### ISSUE THREAD

**Issue by sorobedio** [IshiKura-a/ModelGPT#1]
Thank you for your excellent work!

If I understand correctly, you trained the generator on the GLUE dataset and then used it to retrieve weights for the same dataset based on user requirements. Is that right?
that meant you have one hypernet for glue task one for vision and one for tabular all pretrained on the corresponding tasks in advance. rs that correct?

Regarding runtime measurement, does it include the time taken to generate the weights and perform evaluation? If so, why is this time lower than that of LoRA, considering LoRA is already pretrained?

**Comment by IshiKura-a** [comment]
Hi, thank you for your questions.
> Q1: If I understand correctly, you trained the generator on the GLUE dataset and then used it to retrieve weights for the same dataset based on user requirements.

A1: In the currently released version, we train the generator on GLUE's training data, generate user requirements, and then use user requirements as input to generate weights. So it would be better to call the process "generate" rather than "retrieve", since we don't have similar implementations like RAGs.

Besides, we do have zero-shot tests in the arxiv version (see exps of CV tasks), where, in test, we use data from another domain to get the requirements and weights. We've also trained ModelGPT on ANLI_R1~ANLI_R3 and tested on CB and MNLI (all are NLI tasks), which have comparable results (not released in arxiv version currently).
![zs res](https://github.com/user-attachments/assets/28b88203-59a0-419d-b0bf-68e763c2b714)

> Q2:  you have one hypernet for glue task one for vision and one for tabular all pretrained on the corresponding tasks in advance.

A2: In the currently released version, YES. However, we are planning to solve these tasks from different modalities in one ModelGPT. We kindly invite you to stay tuned for further updates.

> Q3: Regarding runtime measurement, does it include the time taken to generate the weights and perform evaluation? If so, why is this time lower than that of LoRA, considering LoRA is already pretrained?

A3: Yes. However, in test scenes, LoRA needs finetuning, but ModelGPT only needs inference. As a result, LoRA's run time is added with the time of finetuning. So it is slower.

If you are interested in our work, welcome to cite us or star this repo!

**Comment by sorobedio** [comment]
Thank you for the prompt update.
i am already tuned I cannot wait to see the final version.
don't worry I am going to cite your paper.
